/*
 * Copyright (c) 2025 ADBC Drivers Contributors
 *
 * This file has been modified from its original version, which is
 * under the Apache License:
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.21.0)
 * BUT THIS FILE HAS BEEN HAND EDITED TO SUPPORT ARROW AND DISABLE NULLABLE SO REGENERATE AT YOUR OWN RISK
 * </auto-generated>
 */
using System;
using System.IO;
using System.Text;
using System.Threading;
using AdbcDrivers.HiveServer2.Thrift;
using Apache.Arrow;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;

#nullable disable

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable CS0618   // silence our own deprecation warnings
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Apache.Hive.Service.Rpc.Thrift
{

  internal partial class TBoolColumn : TBase
  {

    public BooleanArray Values { get; set; }

    public TBoolColumn()
    {
    }

    public TBoolColumn(BooleanArray values) : this()
    {
      this.Values = values;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_values = false;
        bool isset_nulls = false;
        TField field;

        ArrowBuffer.BitmapBuilder values = null;
        byte[] nulls = null;
        int length = -1;

        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  var _list133 = await iprot.ReadListBeginAsync(cancellationToken);
                  length = _list133.Count;

                  byte[] buffer = new byte[length];
                  var memory = buffer.AsMemory();
                  iprot.Transport.CheckReadBytesAvailable(buffer.Length);
                  await iprot.Transport.ReadExactlyAsync(buffer.AsMemory(0, length), cancellationToken);

                  values = new ArrowBuffer.BitmapBuilder(length);
                  for (int _i134 = 0; _i134 < length; ++_i134)
                  {
                    values.Append(buffer[_i134] == 1);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_values = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                nulls = await iprot.ReadBinaryAsync(cancellationToken);
                isset_nulls = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default:
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_values)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_nulls)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }

        ArrowBuffer validityBitmapBuffer = BitmapUtilities.GetValidityBitmapBuffer(ref nulls, length, out int nullCount);
        Values = new BooleanArray(values.Build(), validityBitmapBuffer, length, nullCount, 0);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp136 = new TStruct("TBoolColumn");
        await oprot.WriteStructBeginAsync(tmp136, cancellationToken);
        var tmp137 = new TField();
        if ((Values != null))
        {
          tmp137.Name = "values";
          tmp137.Type = TType.List;
          tmp137.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp137, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Bool, Values.Length), cancellationToken);
          for (int i = 0; i < Values.Length; i++)
          {
            bool _iter138 = Values.GetValue(i) ?? false;
            await oprot.WriteBoolAsync(_iter138, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);

          tmp137.Name = "nulls";
          tmp137.Type = TType.String;
          tmp137.ID = 2;
          byte[] nulls = new byte[Values.NullBitmapBuffer.Span.Length];
          Values.NullBitmapBuffer.Span.CopyTo(nulls);
          await oprot.WriteFieldBeginAsync(tmp137, cancellationToken);
          await oprot.WriteBinaryAsync(nulls, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is TBoolColumn other)) return false;
      if (ReferenceEquals(this, other)) return true;
      throw new NotImplementedException();
    }

    public override int GetHashCode()
    {
      throw new NotImplementedException();
    }

    public override string ToString()
    {
      var tmp139 = new StringBuilder("TBoolColumn(");
      if ((Values != null))
      {
        tmp139.Append(", Values: ");
        Values.ToString(tmp139);
      }
      tmp139.Append(')');
      return tmp139.ToString();
    }
  }

}
