/*
 * Copyright (c) 2025 ADBC Drivers Contributors
 *
 * This file has been modified from its original version, which is
 * under the Apache License:
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;

// targeting netstandard 2.x
#if(! NETSTANDARD2_0_OR_GREATER && ! NET6_0_OR_GREATER && ! NET472_OR_GREATER)
#error Unexpected target platform. See 'thrift --help' for details.
#endif

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable CS0618   // silence our own deprecation warnings
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Apache.Hive.Service.Rpc.Thrift
{
  internal enum TProtocolVersion
  {
    __HIVE_JDBC_WORKAROUND = -7,
    __TEST_PROTOCOL_VERSION = 65281,
    HIVE_CLI_SERVICE_PROTOCOL_V1 = 0,
    HIVE_CLI_SERVICE_PROTOCOL_V2 = 1,
    HIVE_CLI_SERVICE_PROTOCOL_V3 = 2,
    HIVE_CLI_SERVICE_PROTOCOL_V4 = 3,
    HIVE_CLI_SERVICE_PROTOCOL_V5 = 4,
    HIVE_CLI_SERVICE_PROTOCOL_V6 = 5,
    HIVE_CLI_SERVICE_PROTOCOL_V7 = 6,
    HIVE_CLI_SERVICE_PROTOCOL_V8 = 7,
    HIVE_CLI_SERVICE_PROTOCOL_V9 = 8,
    HIVE_CLI_SERVICE_PROTOCOL_V10 = 9,
    HIVE_CLI_SERVICE_PROTOCOL_V11 = 10,
    SPARK_CLI_SERVICE_PROTOCOL_V1 = 42241,
    SPARK_CLI_SERVICE_PROTOCOL_V2 = 42242,
    SPARK_CLI_SERVICE_PROTOCOL_V3 = 42243,
    SPARK_CLI_SERVICE_PROTOCOL_V4 = 42244,
    SPARK_CLI_SERVICE_PROTOCOL_V5 = 42245,
    SPARK_CLI_SERVICE_PROTOCOL_V6 = 42246,
    SPARK_CLI_SERVICE_PROTOCOL_V7 = 42247,
    SPARK_CLI_SERVICE_PROTOCOL_V8 = 42248,
    SPARK_CLI_SERVICE_PROTOCOL_V9 = 42249,
  }
}
